/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Cyberland Computers
 */
public class addProduct extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    public addProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p5_addProduct = new javax.swing.JPanel();
        header8 = new javax.swing.JPanel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        txtprodname = new javax.swing.JTextField();
        jLabel112 = new javax.swing.JLabel();
        txtprodcompany = new javax.swing.JTextField();
        txtprodprice = new javax.swing.JTextField();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        addProduct = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtprodid = new javax.swing.JTextField();
        jLabel118 = new javax.swing.JLabel();
        txtprodinstock = new javax.swing.JTextField();
        txtprodvend = new javax.swing.JTextField();
        txtprodtype = new javax.swing.JTextField();
        jLabel116 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        header8.setBackground(new java.awt.Color(204, 0, 204));
        header8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        header8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel110.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel110.setForeground(new java.awt.Color(255, 255, 255));
        jLabel110.setText("Add Item");
        header8.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        jLabel111.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel111.setForeground(new java.awt.Color(153, 153, 153));
        jLabel111.setText("Product ID:");

        txtprodname.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtprodname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtprodname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprodnameActionPerformed(evt);
            }
        });

        jLabel112.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(153, 153, 153));
        jLabel112.setText("In Stock:");

        txtprodcompany.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtprodcompany.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtprodcompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprodcompanyActionPerformed(evt);
            }
        });

        txtprodprice.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtprodprice.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtprodprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprodpriceActionPerformed(evt);
            }
        });

        jLabel113.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(153, 153, 153));
        jLabel113.setText("Price :");

        jLabel114.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel114.setForeground(new java.awt.Color(153, 153, 153));
        jLabel114.setText("Company : ");

        jLabel115.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel115.setForeground(new java.awt.Color(153, 153, 153));
        jLabel115.setText("Vendor :");

        addProduct.setBackground(new java.awt.Color(204, 0, 204));
        addProduct.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        addProduct.setForeground(new java.awt.Color(255, 255, 255));
        addProduct.setText("Add Item");
        addProduct.setBorderPainted(false);
        addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 51));
        jButton3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Go Back");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtprodid.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtprodid.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtprodid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprodidActionPerformed(evt);
            }
        });

        jLabel118.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel118.setForeground(new java.awt.Color(153, 153, 153));
        jLabel118.setText("Product Name:");

        txtprodinstock.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtprodinstock.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtprodinstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprodinstockActionPerformed(evt);
            }
        });

        txtprodvend.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtprodvend.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtprodvend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprodvendActionPerformed(evt);
            }
        });

        txtprodtype.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtprodtype.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtprodtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprodtypeActionPerformed(evt);
            }
        });

        jLabel116.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel116.setForeground(new java.awt.Color(153, 153, 153));
        jLabel116.setText("Product Type:");

        javax.swing.GroupLayout p5_addProductLayout = new javax.swing.GroupLayout(p5_addProduct);
        p5_addProduct.setLayout(p5_addProductLayout);
        p5_addProductLayout.setHorizontalGroup(
            p5_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p5_addProductLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(p5_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel112)
                    .addComponent(txtprodcompany, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jLabel114)
                    .addComponent(txtprodid)
                    .addComponent(jLabel111)
                    .addComponent(txtprodinstock))
                .addGap(18, 33, Short.MAX_VALUE)
                .addGroup(p5_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel118)
                    .addComponent(jLabel115)
                    .addComponent(jLabel113)
                    .addComponent(txtprodprice, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(txtprodname, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(txtprodvend))
                .addGap(182, 182, 182))
            .addGroup(p5_addProductLayout.createSequentialGroup()
                .addGroup(p5_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p5_addProductLayout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jLabel116))
                    .addGroup(p5_addProductLayout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addGroup(p5_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprodtype, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        p5_addProductLayout.setVerticalGroup(
            p5_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p5_addProductLayout.createSequentialGroup()
                .addComponent(header8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(p5_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p5_addProductLayout.createSequentialGroup()
                        .addGroup(p5_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel112)
                            .addComponent(jLabel113))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p5_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtprodprice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprodinstock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p5_addProductLayout.createSequentialGroup()
                        .addGroup(p5_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel118)
                            .addComponent(jLabel111))
                        .addGap(18, 18, 18)
                        .addGroup(p5_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtprodid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprodname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)))
                .addGroup(p5_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel114)
                    .addComponent(jLabel115))
                .addGap(18, 18, 18)
                .addGroup(p5_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprodcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprodvend, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel116)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtprodtype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(p5_addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(p5_addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 

        
    private void txtprodnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprodnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodnameActionPerformed

    private void txtprodcompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprodcompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodcompanyActionPerformed

    private void txtprodpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprodpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodpriceActionPerformed

    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
        try{
        int productId = Integer.parseInt(txtprodid.getText());
        String productName = txtprodname.getText();
        String productVendor = txtprodvend.getText();
        String productCompany = txtprodcompany.getText();
        int productInStock = Integer.parseInt(txtprodinstock.getText());
        String productType = txtprodtype.getText();
        int productPrice = Integer.parseInt(txtprodprice.getText());
        Products p = new Products();
        if(p.addProduct(productId, productName, productType, productCompany, productVendor, productInStock, productPrice)){
            JOptionPane.showMessageDialog(null, "Added");
        }else{
            JOptionPane.showMessageDialog(null, "Error");
        }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Empty fields found");
        }
    }//GEN-LAST:event_addProductActionPerformed

    private void txtprodidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprodidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodidActionPerformed

    private void txtprodinstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprodinstockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodinstockActionPerformed

    private void txtprodvendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprodvendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodvendActionPerformed

    private void txtprodtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprodtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodtypeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduct;
    private javax.swing.JPanel header8;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JPanel p5_addProduct;
    private javax.swing.JTextField txtprodcompany;
    private javax.swing.JTextField txtprodid;
    private javax.swing.JTextField txtprodinstock;
    private javax.swing.JTextField txtprodname;
    private javax.swing.JTextField txtprodprice;
    private javax.swing.JTextField txtprodtype;
    private javax.swing.JTextField txtprodvend;
    // End of variables declaration//GEN-END:variables
}
