/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

/**
 *
 * @author Cyberland Computers
 */
public class cartForm extends javax.swing.JFrame {

    /**
     * Creates new form cartForm
     */
    public cartForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblEmpName = new javax.swing.JLabel();
        lblEmpDesignation = new javax.swing.JLabel();
        btnCart = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnLogout1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        centrePanel = new javax.swing.JPanel();
        p3_Cart = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel73 = new javax.swing.JLabel();
        addItem = new javax.swing.JPanel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        updateItem = new javax.swing.JPanel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        p3_newOrder = new javax.swing.JPanel();
        header11 = new javax.swing.JPanel();
        jLabel131 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblproducts = new javax.swing.JTable();
        jLabel134 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel136 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblcart = new javax.swing.JTable();
        p3_orderHistory = new javax.swing.JPanel();
        header12 = new javax.swing.JPanel();
        jLabel141 = new javax.swing.JLabel();
        txtbillReceipt1 = new javax.swing.JTextField();
        jLabel148 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 2, new java.awt.Color(153, 153, 153)));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(153, 0, 153));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icons/User_Icon.png"))); // NOI18N
        sidePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 5, 130, 67));

        lblEmpName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmpName.setForeground(new java.awt.Color(0, 204, 0));
        lblEmpName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpName.setText(Employee.loggedInEmp.getEmpName());
        sidePanel.add(lblEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 130, 15));

        lblEmpDesignation.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblEmpDesignation.setForeground(new java.awt.Color(102, 204, 255));
        lblEmpDesignation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpDesignation.setText(Employee.loggedInEmp.getEmpDesignation());
        sidePanel.add(lblEmpDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 95, 130, 15));

        btnCart.setBackground(java.awt.Color.red);
        btnCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCartMouseClicked(evt);
            }
        });
        btnCart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icons/cart.png"))); // NOI18N
        btnCart.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 40));

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Cart");
        btnCart.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 130, 15));

        sidePanel.add(btnCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 170, 120, 70));

        btnLogout.setBackground(new java.awt.Color(255, 102, 204));
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 102, 204));
        jLabel17.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Log Out");
        jLabel17.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnLogoutLayout = new javax.swing.GroupLayout(btnLogout);
        btnLogout.setLayout(btnLogoutLayout);
        btnLogoutLayout.setHorizontalGroup(
            btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        btnLogoutLayout.setVerticalGroup(
            btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLogoutLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sidePanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 500, 124, 30));

        btnLogout1.setBackground(new java.awt.Color(255, 102, 204));
        btnLogout1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogout1MouseClicked(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 102, 204));
        jLabel18.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Back");
        jLabel18.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnLogout1Layout = new javax.swing.GroupLayout(btnLogout1);
        btnLogout1.setLayout(btnLogout1Layout);
        btnLogout1Layout.setHorizontalGroup(
            btnLogout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLogout1Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        btnLogout1Layout.setVerticalGroup(
            btnLogout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLogout1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sidePanel.add(btnLogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, -1));

        mainPanel.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 600));

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 2, new java.awt.Color(153, 153, 153)));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icons/Cancel_Icon.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        headerPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 5, -1, -1));

        mainPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 900, 35));

        centrePanel.setLayout(new java.awt.CardLayout());

        p3_Cart.setBackground(new java.awt.Color(218, 228, 230));

        jLabel72.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 102, 204));
        jLabel72.setText("ONE MART");

        jLabel73.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel73.setText("Order Section");

        addItem.setBackground(new java.awt.Color(255, 255, 255));
        addItem.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        addItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addItemMouseClicked(evt);
            }
        });
        addItem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel102.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icons/neworder.png"))); // NOI18N
        addItem.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel103.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(51, 204, 0));
        jLabel103.setText("Create Order");
        addItem.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        updateItem.setBackground(new java.awt.Color(255, 255, 255));
        updateItem.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        updateItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateItemMouseClicked(evt);
            }
        });
        updateItem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel104.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icons/order-history.png"))); // NOI18N
        updateItem.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel105.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(0, 102, 153));
        jLabel105.setText("Order History");
        updateItem.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        javax.swing.GroupLayout p3_CartLayout = new javax.swing.GroupLayout(p3_Cart);
        p3_Cart.setLayout(p3_CartLayout);
        p3_CartLayout.setHorizontalGroup(
            p3_CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p3_CartLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(p3_CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3_CartLayout.createSequentialGroup()
                        .addComponent(addItem, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateItem, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel73))
                .addContainerGap())
        );
        p3_CartLayout.setVerticalGroup(
            p3_CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3_CartLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel72)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel73)
                .addGap(18, 18, 18)
                .addGroup(p3_CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateItem, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(230, 230, 230))
        );

        centrePanel.add(p3_Cart, "card2");

        header11.setBackground(new java.awt.Color(204, 0, 204));
        header11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        header11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel131.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel131.setForeground(new java.awt.Color(255, 255, 255));
        jLabel131.setText("Make Order");
        header11.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        tblproducts.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tblproducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Product Type", "Product Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblproducts);

        jLabel134.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel134.setForeground(new java.awt.Color(255, 102, 204));
        jLabel134.setText("PRODUCTS LIST");

        jComboBox1.setBackground(new java.awt.Color(255, 102, 204));
        jComboBox1.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Canned Items", "Frozen Food", "Beverages" }));
        jComboBox1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel136.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel136.setForeground(new java.awt.Color(255, 102, 204));
        jLabel136.setText("Filter By ");

        jLabel138.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel138.setForeground(new java.awt.Color(255, 102, 204));
        jLabel138.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icons/printcart.png"))); // NOI18N
        jLabel138.setText("PRINT RECEIPT");

        jLabel139.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel139.setForeground(new java.awt.Color(255, 102, 204));
        jLabel139.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icons/clearicon.png"))); // NOI18N
        jLabel139.setText("Clear");

        jLabel140.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel140.setForeground(new java.awt.Color(255, 102, 204));
        jLabel140.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icons/addtocart.png"))); // NOI18N
        jLabel140.setText("Add to Cart");

        tblcart.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tblcart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Product Tyep", "Product Quantity", "Product Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tblcart);

        javax.swing.GroupLayout p3_newOrderLayout = new javax.swing.GroupLayout(p3_newOrder);
        p3_newOrder.setLayout(p3_newOrderLayout);
        p3_newOrderLayout.setHorizontalGroup(
            p3_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(p3_newOrderLayout.createSequentialGroup()
                .addGroup(p3_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3_newOrderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel136, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p3_newOrderLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel134, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p3_newOrderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p3_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel140, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel139, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p3_newOrderLayout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel138)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p3_newOrderLayout.setVerticalGroup(
            p3_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3_newOrderLayout.createSequentialGroup()
                .addComponent(header11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(p3_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(p3_newOrderLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel140)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel139))
                    .addGroup(p3_newOrderLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(p3_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(p3_newOrderLayout.createSequentialGroup()
                                .addComponent(jLabel134)
                                .addGap(24, 24, 24)
                                .addGroup(p3_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel136)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addComponent(jLabel138, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        centrePanel.add(p3_newOrder, "card7");

        header12.setBackground(new java.awt.Color(204, 0, 204));
        header12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        header12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel141.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel141.setForeground(new java.awt.Color(255, 255, 255));
        jLabel141.setText("ORDER HISTORY");
        header12.add(jLabel141, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        txtbillReceipt1.setText("********************************BILLING POINT************************");
        txtbillReceipt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbillReceipt1ActionPerformed(evt);
            }
        });

        jLabel148.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel148.setForeground(new java.awt.Color(255, 102, 204));
        jLabel148.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icons/printcart.png"))); // NOI18N
        jLabel148.setText("PRINT RECEIPT");

        javax.swing.GroupLayout p3_orderHistoryLayout = new javax.swing.GroupLayout(p3_orderHistory);
        p3_orderHistory.setLayout(p3_orderHistoryLayout);
        p3_orderHistoryLayout.setHorizontalGroup(
            p3_orderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header12, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
            .addGroup(p3_orderHistoryLayout.createSequentialGroup()
                .addGroup(p3_orderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3_orderHistoryLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(txtbillReceipt1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p3_orderHistoryLayout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel148)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p3_orderHistoryLayout.setVerticalGroup(
            p3_orderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3_orderHistoryLayout.createSequentialGroup()
                .addComponent(header12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtbillReceipt1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel148, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );

        centrePanel.add(p3_orderHistory, "card7");

        mainPanel.add(centrePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 35, 769, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCartMouseClicked
        p3_Cart.show(true);
    }//GEN-LAST:event_btnCartMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnLogoutMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void addItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addItemMouseClicked

        Products p = new Products();
        p.loadProducts();
        new createOrder().setVisible(true);
    }//GEN-LAST:event_addItemMouseClicked

    private void txtbillReceipt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbillReceipt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbillReceipt1ActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        Employee.loggedInEmp.setEmpName("");
        Employee.loggedInEmp.setEmpId(0);
        Employee.loggedInEmp.setEmpAccessLevel(0);
        Employee.loggedInEmp.setEmpDesignation("");
        Employee.loggedInEmp.setEmpSalary("");
        Employee.loggedInEmp.setEmpPassword("");
        Employee.loggedInEmp.setEmpContact("");
        Products.clearArrays();
        new loginForm().show(true);
        dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void updateItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateItemMouseClicked
        new previousOrders().show(true);
    }//GEN-LAST:event_updateItemMouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        new loginSelectorForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void btnLogout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogout1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogout1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cartForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addItem;
    private javax.swing.JPanel btnCart;
    private javax.swing.JPanel btnLogout;
    private javax.swing.JPanel btnLogout1;
    private javax.swing.JPanel centrePanel;
    private javax.swing.JPanel header11;
    private javax.swing.JPanel header12;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblEmpDesignation;
    private javax.swing.JLabel lblEmpName;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel p3_Cart;
    private javax.swing.JPanel p3_newOrder;
    private javax.swing.JPanel p3_orderHistory;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTable tblcart;
    private javax.swing.JTable tblproducts;
    private javax.swing.JTextField txtbillReceipt1;
    private javax.swing.JPanel updateItem;
    // End of variables declaration//GEN-END:variables
}
