/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import static Main.Products.nameList;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cyberland Computers
 */
public class createOrder extends javax.swing.JFrame {

    /**
     * Creates new form cartForm
     */
    public createOrder() {
        initComponents();
        addProd();
    }
    public void addProd(){
        DefaultTableModel model = (DefaultTableModel) tblproducts.getModel();
        Object rowData[] = new Object[3];
        for (int i = 0; i < nameList.size(); i++) {
            rowData[0] = Products.nameList.get(i);
            rowData[1] = Products.typeList.get(i);
            rowData[2] = Products.priceList.get(i);
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p3_newOrder = new javax.swing.JPanel();
        header11 = new javax.swing.JPanel();
        jLabel131 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblproducts = new javax.swing.JTable();
        jLabel134 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblcart = new javax.swing.JTable();
        jLabel135 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        searchtxt = new javax.swing.JTextField();
        deleteProduct = new javax.swing.JButton();
        txttotal = new javax.swing.JTextField();
        jLabel139 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        header11.setBackground(new java.awt.Color(204, 0, 204));
        header11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        header11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel131.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel131.setForeground(new java.awt.Color(255, 255, 255));
        jLabel131.setText("Make Order");
        header11.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        tblproducts.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tblproducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Product Type", "Product Price ($)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblproducts);
        if (tblproducts.getColumnModel().getColumnCount() > 0) {
            tblproducts.getColumnModel().getColumn(0).setResizable(false);
            tblproducts.getColumnModel().getColumn(1).setResizable(false);
            tblproducts.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel134.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel134.setForeground(new java.awt.Color(255, 102, 204));
        jLabel134.setText("Cart");

        jLabel136.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel136.setForeground(new java.awt.Color(255, 102, 204));
        jLabel136.setText("Search By Name");

        jLabel138.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel138.setForeground(new java.awt.Color(255, 102, 204));
        jLabel138.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icons/printcart.png"))); // NOI18N
        jLabel138.setText("PRINT RECEIPT");
        jLabel138.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel138MouseClicked(evt);
            }
        });

        jLabel140.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel140.setForeground(new java.awt.Color(255, 102, 204));
        jLabel140.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icons/addtocart.png"))); // NOI18N
        jLabel140.setText("Add to Cart");
        jLabel140.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel140MouseClicked(evt);
            }
        });

        tblcart.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tblcart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Product Tyep", "Product Quantity", "Product Price ($)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tblcart);

        jLabel135.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel135.setForeground(new java.awt.Color(255, 102, 204));
        jLabel135.setText("PRODUCTS LIST");

        jLabel141.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel141.setForeground(new java.awt.Color(255, 102, 204));
        jLabel141.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icons/clearicon.png"))); // NOI18N
        jLabel141.setText("Remove From Cart");
        jLabel141.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel141MouseClicked(evt);
            }
        });

        jLabel137.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel137.setForeground(java.awt.Color.red);
        jLabel137.setText("Back");
        jLabel137.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel137MouseClicked(evt);
            }
        });

        searchtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtxtActionPerformed(evt);
            }
        });

        deleteProduct.setBackground(new java.awt.Color(204, 0, 204));
        deleteProduct.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        deleteProduct.setForeground(new java.awt.Color(255, 255, 255));
        deleteProduct.setText("Go");
        deleteProduct.setBorderPainted(false);
        deleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductActionPerformed(evt);
            }
        });

        txttotal.setEditable(false);
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        jLabel139.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel139.setForeground(new java.awt.Color(255, 102, 204));
        jLabel139.setText("Total");

        javax.swing.GroupLayout p3_newOrderLayout = new javax.swing.GroupLayout(p3_newOrder);
        p3_newOrder.setLayout(p3_newOrderLayout);
        p3_newOrderLayout.setHorizontalGroup(
            p3_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(p3_newOrderLayout.createSequentialGroup()
                .addGroup(p3_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3_newOrderLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel138)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(p3_newOrderLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel137)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel141))
                    .addGroup(p3_newOrderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p3_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(p3_newOrderLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel135, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel134)
                                .addGap(135, 135, 135))
                            .addGroup(p3_newOrderLayout.createSequentialGroup()
                                .addGroup(p3_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p3_newOrderLayout.createSequentialGroup()
                                        .addComponent(jLabel136)
                                        .addGap(18, 18, 18)
                                        .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(deleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(p3_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel140, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(txttotal)
                                    .addGroup(p3_newOrderLayout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel139)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        p3_newOrderLayout.setVerticalGroup(
            p3_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3_newOrderLayout.createSequentialGroup()
                .addComponent(header11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(p3_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel135)
                    .addComponent(jLabel134))
                .addGap(9, 9, 9)
                .addGroup(p3_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel136)
                    .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(p3_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p3_newOrderLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel140)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel139)
                        .addGap(18, 18, 18)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)))
                .addGap(18, 18, 18)
                .addGroup(p3_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel141)
                    .addComponent(jLabel137))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel138, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p3_newOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(p3_newOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel137MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel137MouseClicked
        DefaultTableModel model = (DefaultTableModel) tblproducts.getModel();
        model.setRowCount(0);
        Products.inStockList.clear();
        Products.nameList.clear();
        Products.priceList.clear();
        dispose();
    }//GEN-LAST:event_jLabel137MouseClicked

    private void jLabel140MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel140MouseClicked

        ArrayList<String> name = new ArrayList();
        ArrayList<String> type = new ArrayList();
        ArrayList<Integer> price = new ArrayList();
        ArrayList<Integer> quantity = new ArrayList();
        for (int i = 0; i < tblcart.getRowCount(); i++) {
            name.add(String.valueOf(tblcart.getValueAt(i, 0)));
            type.add(String.valueOf(tblcart.getValueAt(i, 1)));
            quantity.add(Integer.parseInt(""+tblcart.getValueAt(i, 2)));
            price.add(Integer.parseInt(""+tblcart.getValueAt(i, 3)));
        }
        int selected = tblproducts.getSelectedRow();
        String selectname = String.valueOf(tblproducts.getValueAt(selected, 0));
        String selecttype = String.valueOf(tblproducts.getValueAt(selected, 1));
        int selectprice = Integer.parseInt(""+tblproducts.getValueAt(selected, 2));
        if(name.indexOf(selectname) != -1){
            quantity.set(name.indexOf(selectname), (quantity.get(name.indexOf(selectname)))+1);
            price.set(name.indexOf(selectname), (Products.priceList.get(Products.nameList.indexOf(selectname)))*quantity.get(name.indexOf(selectname)));
            }else{
            name.add(selectname);
            type.add(selecttype);
            price.add(selectprice);
            quantity.add(1);
        
        }
        DefaultTableModel model = (DefaultTableModel) tblcart.getModel();
        model.setRowCount(0);
        Object rowData[] = new Object[4];
        for (int i = 0; i < name.size(); i++) {
            rowData[0] = name.get(i);
            rowData[1] = type.get(i);
            rowData[2] = quantity.get(i);
            rowData[3] = price.get(i);
            model.addRow(rowData);
        }
        int total = 0;
        for (int i = 0; i < price.size(); i++) {
            total += price.get(i);
        }
        txttotal.setText("" + total);
    }//GEN-LAST:event_jLabel140MouseClicked

    private void jLabel141MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel141MouseClicked
        ArrayList<String> name = new ArrayList();
        ArrayList<String> type = new ArrayList();
        ArrayList<Integer> price = new ArrayList();
        ArrayList<Integer> quantity = new ArrayList();
        for (int i = 0; i < tblcart.getRowCount(); i++) {
            name.add(String.valueOf(tblcart.getValueAt(i, 0)));
            type.add(String.valueOf(tblcart.getValueAt(i, 1)));
            quantity.add(Integer.parseInt(""+tblcart.getValueAt(i, 2)));
            price.add(Integer.parseInt(""+tblcart.getValueAt(i, 3)));
        }
        int selected = tblcart.getSelectedRow();
        String selectname = String.valueOf(tblcart.getValueAt(selected, 0));
        int selectquantity = Integer.parseInt(""+tblcart.getValueAt(selected, 2));
        if (selectquantity > 1) {
            quantity.set(name.indexOf(selectname), (quantity.get(name.indexOf(selectname)))-1);
            price.set(name.indexOf(selectname), (Products.priceList.get(Products.nameList.indexOf(selectname)))*quantity.get(name.indexOf(selectname)));
        }else{
            try{
                int rem = 0;
                rem = name.indexOf(selectname);
                name.remove(rem);
                type.remove(rem);
                quantity.remove(rem);
                price.remove(rem);
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        DefaultTableModel model = (DefaultTableModel) tblcart.getModel();
        model.setRowCount(0);
        Object rowData[] = new Object[4];
        for (int i = 0; i < name.size(); i++) {
            rowData[0] = name.get(i);
            rowData[1] = type.get(i);
            rowData[2] = quantity.get(i);
            rowData[3] = price.get(i);
            model.addRow(rowData);
        }
        int total = 0;
        for (int i = 0; i < price.size(); i++) {
            total += price.get(i);
        }
        txttotal.setText("" + total);
    }//GEN-LAST:event_jLabel141MouseClicked

    private void searchtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtxtActionPerformed

    private void deleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductActionPerformed
        String search = searchtxt.getText();
        Products p = new Products();
        if(search.equals("")){
            Products.nameList.clear();
            Products.priceList.clear();
            Products.inStockList.clear();
            Products.typeList.clear();
            p.loadProducts();
            DefaultTableModel model = (DefaultTableModel) tblproducts.getModel();
            model.setRowCount(0);
            addProd();
        }else{
            Products.nameList.clear();
            Products.priceList.clear();
            Products.inStockList.clear();
            Products.typeList.clear();
            p.loadNameFilter(search);
            DefaultTableModel model = (DefaultTableModel) tblproducts.getModel();
            model.setRowCount(0);
            addProd();
        }
        
    }//GEN-LAST:event_deleteProductActionPerformed

    private void jLabel138MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel138MouseClicked
        ArrayList<String> name = new ArrayList();
        ArrayList<String> type = new ArrayList();
        ArrayList<Integer> price = new ArrayList();
        ArrayList<Integer> quantity = new ArrayList();
        for (int i = 0; i < tblcart.getRowCount(); i++) {
            name.add(String.valueOf(tblcart.getValueAt(i, 0)));
            type.add(String.valueOf(tblcart.getValueAt(i, 1)));
            quantity.add(Integer.parseInt(""+tblcart.getValueAt(i, 2)));
            price.add(Integer.parseInt(""+tblcart.getValueAt(i, 3)));
        }
        Cart c = new Cart();
        c.setOrderTotal(Integer.parseInt(txttotal.getText()));
        c.setEmployeeName(Employee.loggedInEmp.getEmpName());
        for (int i = 0; i < name.size(); i++) {
            c.addProductNames(name.get(i));
        }
        for (int i = 0; i < type.size(); i++) {
            c.addProductTypes(type.get(i));
        }
        for (int i = 0; i < price.size(); i++) {
            c.addProductPrice(price.get(i));
        }
        for (int i = 0; i < quantity.size(); i++) {
            c.addProductQuantity(quantity.get(i));
        }
        Products p = new Products();
        for (int i = 0; i < name.size(); i++) {
            p.updUnitsSold(name.get(i), quantity.get(i));
            p.updStock(name.get(i), quantity.get(i));
        }
        try{
            Finances f = new Finances();
            f.updateincome(Integer.parseInt(txttotal.getText()));
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        new orderConfirm().setVisible(true);
    }//GEN-LAST:event_jLabel138MouseClicked

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteProduct;
    private javax.swing.JPanel header11;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel p3_newOrder;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JTable tblcart;
    private javax.swing.JTable tblproducts;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
