/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cyberland Computers
 */
public class generateSalary extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    public generateSalary() {
        initComponents();
        addNameToTable();
        total();
    }
    public void addNameToTable(){
        DefaultTableModel model = (DefaultTableModel) EmpSalaryTable.getModel();
        Object rowData[] = new Object[3];
        for (int i = 0; i < Employee.employeeNameList.size(); i++) {
            rowData[0] = Employee.employeeNameList.get(i);
            rowData[1] = Employee.employeeDesigList.get(i);
            rowData[2] = Employee.employeeSalaryList.get(i);
            model.addRow(rowData);
        }
    }
    public void total(){
        int total = 0;
        for (int i = 0; i < Employee.employeeSalaryList.size(); i++) {
            total += Employee.employeeSalaryList.get(i);
        }
        txttotal.setText("" + total);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p5_searchProduct = new javax.swing.JPanel();
        header11 = new javax.swing.JPanel();
        jLabel131 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        EmpSalaryTable = new javax.swing.JTable();
        jLabel134 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        btnpayout = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        header11.setBackground(new java.awt.Color(204, 0, 204));
        header11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        header11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel131.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel131.setForeground(new java.awt.Color(255, 255, 255));
        jLabel131.setText("Fetch Item");
        header11.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        EmpSalaryTable.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        EmpSalaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Name", "Employee Designation", "Employee Salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(EmpSalaryTable);

        jLabel134.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel134.setForeground(new java.awt.Color(153, 153, 153));
        jLabel134.setText("Employee List");

        txttotal.setEditable(false);
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        btnpayout.setBackground(new java.awt.Color(204, 0, 204));
        btnpayout.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnpayout.setForeground(new java.awt.Color(255, 255, 255));
        btnpayout.setText("Payout");
        btnpayout.setBorderPainted(false);
        btnpayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpayoutActionPerformed(evt);
            }
        });

        btnback.setBackground(new java.awt.Color(255, 0, 51));
        btnback.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.setBorderPainted(false);
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p5_searchProductLayout = new javax.swing.GroupLayout(p5_searchProduct);
        p5_searchProduct.setLayout(p5_searchProductLayout);
        p5_searchProductLayout.setHorizontalGroup(
            p5_searchProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
            .addGroup(p5_searchProductLayout.createSequentialGroup()
                .addGroup(p5_searchProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p5_searchProductLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel134, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p5_searchProductLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnpayout)
                        .addGap(18, 18, 18)
                        .addComponent(btnback)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        p5_searchProductLayout.setVerticalGroup(
            p5_searchProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p5_searchProductLayout.createSequentialGroup()
                .addComponent(header11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel134)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(p5_searchProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpayout, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(p5_searchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(p5_searchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void btnpayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpayoutActionPerformed
        int amount = Integer.parseInt(txttotal.getText());
        Finances f = new Finances();
        try{
        f.updateoutflow(amount);
        }catch(Exception ex){
            JOptionPane.showConfirmDialog(null, ex);
        }
        JOptionPane.showMessageDialog(null, "Paid");
        System.out.println(f.getOutflow());
        DefaultTableModel model = (DefaultTableModel) EmpSalaryTable.getModel();
        model.setRowCount(0);
        Employee.employeeNameList.clear();
        Employee.employeeDesigList.clear();
        Employee.employeeSalaryList.clear();
        dispose();
    }//GEN-LAST:event_btnpayoutActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        DefaultTableModel model = (DefaultTableModel) EmpSalaryTable.getModel();
        model.setRowCount(0);
        Employee.employeeNameList.clear();
        Employee.employeeDesigList.clear();
        Employee.employeeSalaryList.clear();
        dispose();
    }//GEN-LAST:event_btnbackActionPerformed
 

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(generateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(generateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(generateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(generateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new generateSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EmpSalaryTable;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnpayout;
    private javax.swing.JPanel header11;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel p5_searchProduct;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
